baseURL = "https://laomeinote.com"
relativeURLs = false
title = "老梅笔记"
theme = "zzo"

defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = false
hasCJKLanguage = true

summaryLength = 70
buildFuture = true

copyright = "&copy;{year}, All Rights Reserved"
timeout = 10000
enableEmoji = true
paginate = 10
rssLimit = 100

enableGitInfo = false
googleAnalytics = ""

[params]
  [params.headers]
    Access-Control-Allow-Origin = "https://laomeinote.com"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xHTML = true
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[outputs]
  home = ["HTML", "SearchIndex"]
  section = ["HTML",  "SearchIndex"]
  taxonomyTerm = ["HTML", "SearchIndex"]
  taxonomy = ["HTML", "SearchIndex"]

[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
