[[main]]
  identifier = "home"
  name = "首页"
  url = "/"
  weight = 1

[[main]]
  identifier = "archive"
  name = "归档"
  url = "archive"
  weight = 2

[[main]]
  identifier = "about"
  name = "关于"
  url = "about"
  weight = 4

[[main]]
  identifier = "tools"
  name = "工具"
  url = "/"
  weight = 5
    
[[main]]
  parent = "tools"
  name = "google"
  url = "categories/google/"

[[main]]
  parent = "tools"
  name = "chatgpt"
  url = "categories/chatgpt/"