[[main]]
  identifier = "home"
  name = "首页"
  url = "/"
  weight = 1

[[main]]
  identifier = "archive"
  name = "时光机"
  url = "archive"
  weight = 2

[[main]]
  identifier = "about"
  name = "关于"
  url = "/about/"
  weight = 3