[[main]]
  identifier = "home"
  name = "首页"
  url = "/"
  weight = 1

[[main]]
  identifier = "archive"
  name = "时光机"
  url = "archive"
  weight = 2

[[main]]
  identifier = "chatgpt"
  name = "chatgpt"
  url = "chatgpt"
  weight = 4
    
[[main]]
  parent = "chatgpt"
  name = "chatweb"
  url = "https://chatnext.laomeinote.com"

[[main]]
  parent = "chatgpt"
  name = "chatnext"
  url = "https://chatnext.laomeinote.com"