# 通过 Github action， 在仓库的每一次 commit 后自动同步到 Gitee 上
name: sync2gitee
on:
  push:
    branches:
      - master 
jobs:
  repo-sync:
    env:
      SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          
      - name: Configure Git
        run: |
           git config --global --add safe.directory /github/workspace

      - name: sync github -> gitee
        uses: wearerequired/git-mirror-action@master
        if: env.SSH_PRIVATE_KEY
        with:
          source-repo: "git@github.com:${{ github.repository }}.git"
          destination-repo: "git@gitee.com:meixuhong/laomeinote.com.git"